# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI\Aslab_EditJob.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(644, 504)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.jobNameEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.jobNameEdit_2.setObjectName("jobNameEdit_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.jobNameEdit_2)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.jobDescEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.jobDescEdit_2.setObjectName("jobDescEdit_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.jobDescEdit_2)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.IntervalRadioBtn_2 = QtWidgets.QRadioButton(Dialog)
        self.IntervalRadioBtn_2.setText("")
        self.IntervalRadioBtn_2.setObjectName("IntervalRadioBtn_2")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.IntervalRadioBtn_2)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit_2)
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.minutesSpinBox_2 = QtWidgets.QSpinBox(Dialog)
        self.minutesSpinBox_2.setObjectName("minutesSpinBox_2")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.minutesSpinBox_2)
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.daysSpinBox_2 = QtWidgets.QSpinBox(Dialog)
        self.daysSpinBox_2.setObjectName("daysSpinBox_2")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.daysSpinBox_2)
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setObjectName("label_19")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.hoursSpinBox_2 = QtWidgets.QSpinBox(Dialog)
        self.hoursSpinBox_2.setObjectName("hoursSpinBox_2")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.hoursSpinBox_2)
        self.weeksSpinBox_2 = QtWidgets.QSpinBox(Dialog)
        self.weeksSpinBox_2.setObjectName("weeksSpinBox_2")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.weeksSpinBox_2)
        self.manualJobAddBtn_2 = QtWidgets.QPushButton(Dialog)
        self.manualJobAddBtn_2.setObjectName("manualJobAddBtn_2")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.manualJobAddBtn_2)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.secondsSpinBox_2 = QtWidgets.QSpinBox(Dialog)
        self.secondsSpinBox_2.setObjectName("secondsSpinBox_2")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.secondsSpinBox_2)
        self.label_7 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_7)
        self.horizontalLayout.addLayout(self.formLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Name"))
        self.label_5.setText(_translate("Dialog", "Description"))
        self.label_15.setText(_translate("Dialog", "Date/Time"))
        self.label_16.setText(_translate("Dialog", "Interval"))
        self.dateTimeEdit_2.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy HH:mm:ss"))
        self.label_17.setText(_translate("Dialog", "Minutes"))
        self.label_18.setText(_translate("Dialog", "Days"))
        self.label_19.setText(_translate("Dialog", "Hours"))
        self.label_20.setText(_translate("Dialog", "Weeks"))
        self.manualJobAddBtn_2.setText(_translate("Dialog", "Add"))
        self.label_6.setText(_translate("Dialog", "Seconds"))
        self.label_7.setText(_translate("Dialog", "Edit Job"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
